(function() {var implementors = {};
implementors["i2c_linux_sys"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"i2c_linux_sys/struct.Flags.html\" title=\"struct i2c_linux_sys::Flags\">Flags</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"i2c_linux_sys/struct.Functionality.html\" title=\"struct i2c_linux_sys::Functionality\">Functionality</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"i2c_linux_sys/enum.SmbusReadWrite.html\" title=\"enum i2c_linux_sys::SmbusReadWrite\">SmbusReadWrite</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"i2c_linux_sys/enum.SmbusTransaction.html\" title=\"enum i2c_linux_sys::SmbusTransaction\">SmbusTransaction</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"i2c_linux_sys/struct.i2c_msg.html\" title=\"struct i2c_linux_sys::i2c_msg\">i2c_msg</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"i2c_linux_sys/struct.i2c_rdwr_ioctl_data.html\" title=\"struct i2c_linux_sys::i2c_rdwr_ioctl_data\">i2c_rdwr_ioctl_data</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"i2c_linux_sys/struct.i2c_smbus_data.html\" title=\"struct i2c_linux_sys::i2c_smbus_data\">i2c_smbus_data</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"i2c_linux_sys/struct.i2c_smbus_ioctl_data.html\" title=\"struct i2c_linux_sys::i2c_smbus_ioctl_data\">i2c_smbus_ioctl_data</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
